### ISSUE TITLE
build web app using SPA (Single Page Application) Protocol

### ISSUE THREAD

**Issue by stang91** [stang91/movie-recommendation-gen#20]
https://en.wikipedia.org/wiki/Single-page_application

easy flow of UI/UX

https://www.youtube.com/watch?v=JmSb1VFoP7w&ab_channel=DevDrawer

better SPA 
part 1
https://www.youtube.com/watch?v=6BozpmSjk-Y&t=256s&ab_channel=dcode
part 2
https://www.youtube.com/watch?v=OstALBk-jTc&t=0s&ab_channel=dcode

**Comment by shuczhu** [comment]
Great idea!
