### ISSUE TITLE
create js sections and delegates

### ISSUE THREAD

**Issue by stang91** [stang91/movie-recommendation-gen#4]

**Comment by shuczhu** [comment]
Should we use this section to discuss what we hope to get done in terms of js?

I think we should discuss the specifics of discovery method. How do we generate both randomly and also closely relate to user’s preference. I’m thinking there can be more parameters than current. We also talked about having users complete a quiz before. I think this is a good opportunity to learn about building recommendation tools

**Comment by shuczhu** [comment]
Should we use this section to discuss what we hope to get done in terms of js?

I think we should discuss the specifics of discovery method. How do we generate both randomly and also closely relate to user’s preference. I’m thinking there can be more parameters than current. We also talked about having users complete a quiz before. I think this is a good opportunity to learn about building recommendation tools
